#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motor_Maleke_
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MotorcycleRepair")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDetailProduct(DetailProduct instance);
    partial void UpdateDetailProduct(DetailProduct instance);
    partial void DeleteDetailProduct(DetailProduct instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertTransactionService(TransactionService instance);
    partial void UpdateTransactionService(TransactionService instance);
    partial void DeleteTransactionService(TransactionService instance);
    partial void InsertMotorcycleService(MotorcycleService instance);
    partial void UpdateMotorcycleService(MotorcycleService instance);
    partial void DeleteMotorcycleService(MotorcycleService instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    partial void InsertMechanic(Mechanic instance);
    partial void UpdateMechanic(Mechanic instance);
    partial void DeleteMechanic(Mechanic instance);
    partial void InsertDetailService(DetailService instance);
    partial void UpdateDetailService(DetailService instance);
    partial void DeleteDetailService(DetailService instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Motor_Maleke_.Properties.Settings.Default.MotorcycleRepairConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DetailProduct> DetailProducts
		{
			get
			{
				return this.GetTable<DetailProduct>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<TransactionService> TransactionServices
		{
			get
			{
				return this.GetTable<TransactionService>();
			}
		}
		
		public System.Data.Linq.Table<MotorcycleService> MotorcycleServices
		{
			get
			{
				return this.GetTable<MotorcycleService>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
		
		public System.Data.Linq.Table<Mechanic> Mechanics
		{
			get
			{
				return this.GetTable<Mechanic>();
			}
		}
		
		public System.Data.Linq.Table<DetailService> DetailServices
		{
			get
			{
				return this.GetTable<DetailService>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DetailProduct")]
	public partial class DetailProduct : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TransactionNumber;
		
		private string _ProductCode;
		
		private System.Nullable<int> _Price;
		
		private System.Nullable<int> _Amount;
		
		private System.Nullable<int> _Total;
		
		private EntityRef<TransactionService> _TransactionService;
		
		private EntityRef<Product> _Product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTransactionNumberChanging(string value);
    partial void OnTransactionNumberChanged();
    partial void OnProductCodeChanging(string value);
    partial void OnProductCodeChanged();
    partial void OnPriceChanging(System.Nullable<int> value);
    partial void OnPriceChanged();
    partial void OnAmountChanging(System.Nullable<int> value);
    partial void OnAmountChanged();
    partial void OnTotalChanging(System.Nullable<int> value);
    partial void OnTotalChanged();
    #endregion
		
		public DetailProduct()
		{
			this._TransactionService = default(EntityRef<TransactionService>);
			this._Product = default(EntityRef<Product>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionNumber", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TransactionNumber
		{
			get
			{
				return this._TransactionNumber;
			}
			set
			{
				if ((this._TransactionNumber != value))
				{
					if (this._TransactionService.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTransactionNumberChanging(value);
					this.SendPropertyChanging();
					this._TransactionNumber = value;
					this.SendPropertyChanged("TransactionNumber");
					this.OnTransactionNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					if (this._Product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductCodeChanging(value);
					this.SendPropertyChanging();
					this._ProductCode = value;
					this.SendPropertyChanged("ProductCode");
					this.OnProductCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int")]
		public System.Nullable<int> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Int")]
		public System.Nullable<int> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TransactionService_DetailProduct", Storage="_TransactionService", ThisKey="TransactionNumber", OtherKey="TransactionNumber", IsForeignKey=true)]
		public TransactionService TransactionService
		{
			get
			{
				return this._TransactionService.Entity;
			}
			set
			{
				TransactionService previousValue = this._TransactionService.Entity;
				if (((previousValue != value) 
							|| (this._TransactionService.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TransactionService.Entity = null;
						previousValue.DetailProducts.Remove(this);
					}
					this._TransactionService.Entity = value;
					if ((value != null))
					{
						value.DetailProducts.Add(this);
						this._TransactionNumber = value.TransactionNumber;
					}
					else
					{
						this._TransactionNumber = default(string);
					}
					this.SendPropertyChanged("TransactionService");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_DetailProduct", Storage="_Product", ThisKey="ProductCode", OtherKey="ProductCode", IsForeignKey=true)]
		public Product Product
		{
			get
			{
				return this._Product.Entity;
			}
			set
			{
				Product previousValue = this._Product.Entity;
				if (((previousValue != value) 
							|| (this._Product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Product.Entity = null;
						previousValue.DetailProducts.Remove(this);
					}
					this._Product.Entity = value;
					if ((value != null))
					{
						value.DetailProducts.Add(this);
						this._ProductCode = value.ProductCode;
					}
					else
					{
						this._ProductCode = default(string);
					}
					this.SendPropertyChanged("Product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserCode;
		
		private string _UserName;
		
		private string _UserPassword;
		
		private EntitySet<TransactionService> _TransactionServices;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserCodeChanging(string value);
    partial void OnUserCodeChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnUserPasswordChanging(string value);
    partial void OnUserPasswordChanged();
    #endregion
		
		public User()
		{
			this._TransactionServices = new EntitySet<TransactionService>(new Action<TransactionService>(this.attach_TransactionServices), new Action<TransactionService>(this.detach_TransactionServices));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this.OnUserCodeChanging(value);
					this.SendPropertyChanging();
					this._UserCode = value;
					this.SendPropertyChanged("UserCode");
					this.OnUserCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(60)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPassword", DbType="VarChar(50)")]
		public string UserPassword
		{
			get
			{
				return this._UserPassword;
			}
			set
			{
				if ((this._UserPassword != value))
				{
					this.OnUserPasswordChanging(value);
					this.SendPropertyChanging();
					this._UserPassword = value;
					this.SendPropertyChanged("UserPassword");
					this.OnUserPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_TransactionService", Storage="_TransactionServices", ThisKey="UserCode", OtherKey="UserCode")]
		public EntitySet<TransactionService> TransactionServices
		{
			get
			{
				return this._TransactionServices;
			}
			set
			{
				this._TransactionServices.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TransactionServices(TransactionService entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_TransactionServices(TransactionService entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TransactionService")]
	public partial class TransactionService : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TransactionNumber;
		
		private System.Nullable<System.DateTime> _TransactionDate;
		
		private string _PoliceRegistrationNumber;
		
		private string _Damage;
		
		private System.Nullable<int> _TotalServiceCost;
		
		private System.Nullable<int> _TotalProductPrice;
		
		private System.Nullable<int> _TotalCharge;
		
		private System.Nullable<int> _Paid;
		
		private System.Nullable<int> _ChangeMoney;
		
		private string _UserCode;
		
		private string _MechanicCode;
		
		private EntitySet<DetailProduct> _DetailProducts;
		
		private EntitySet<DetailService> _DetailServices;
		
		private EntityRef<User> _User;
		
		private EntityRef<Mechanic> _Mechanic;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTransactionNumberChanging(string value);
    partial void OnTransactionNumberChanged();
    partial void OnTransactionDateChanging(System.Nullable<System.DateTime> value);
    partial void OnTransactionDateChanged();
    partial void OnPoliceRegistrationNumberChanging(string value);
    partial void OnPoliceRegistrationNumberChanged();
    partial void OnDamageChanging(string value);
    partial void OnDamageChanged();
    partial void OnTotalServiceCostChanging(System.Nullable<int> value);
    partial void OnTotalServiceCostChanged();
    partial void OnTotalProductPriceChanging(System.Nullable<int> value);
    partial void OnTotalProductPriceChanged();
    partial void OnTotalChargeChanging(System.Nullable<int> value);
    partial void OnTotalChargeChanged();
    partial void OnPaidChanging(System.Nullable<int> value);
    partial void OnPaidChanged();
    partial void OnChangeMoneyChanging(System.Nullable<int> value);
    partial void OnChangeMoneyChanged();
    partial void OnUserCodeChanging(string value);
    partial void OnUserCodeChanged();
    partial void OnMechanicCodeChanging(string value);
    partial void OnMechanicCodeChanged();
    #endregion
		
		public TransactionService()
		{
			this._DetailProducts = new EntitySet<DetailProduct>(new Action<DetailProduct>(this.attach_DetailProducts), new Action<DetailProduct>(this.detach_DetailProducts));
			this._DetailServices = new EntitySet<DetailService>(new Action<DetailService>(this.attach_DetailServices), new Action<DetailService>(this.detach_DetailServices));
			this._User = default(EntityRef<User>);
			this._Mechanic = default(EntityRef<Mechanic>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionNumber", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TransactionNumber
		{
			get
			{
				return this._TransactionNumber;
			}
			set
			{
				if ((this._TransactionNumber != value))
				{
					this.OnTransactionNumberChanging(value);
					this.SendPropertyChanging();
					this._TransactionNumber = value;
					this.SendPropertyChanged("TransactionNumber");
					this.OnTransactionNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionDate", DbType="Date")]
		public System.Nullable<System.DateTime> TransactionDate
		{
			get
			{
				return this._TransactionDate;
			}
			set
			{
				if ((this._TransactionDate != value))
				{
					this.OnTransactionDateChanging(value);
					this.SendPropertyChanging();
					this._TransactionDate = value;
					this.SendPropertyChanged("TransactionDate");
					this.OnTransactionDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PoliceRegistrationNumber", DbType="VarChar(10)")]
		public string PoliceRegistrationNumber
		{
			get
			{
				return this._PoliceRegistrationNumber;
			}
			set
			{
				if ((this._PoliceRegistrationNumber != value))
				{
					this.OnPoliceRegistrationNumberChanging(value);
					this.SendPropertyChanging();
					this._PoliceRegistrationNumber = value;
					this.SendPropertyChanged("PoliceRegistrationNumber");
					this.OnPoliceRegistrationNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Damage", DbType="VarChar(250)")]
		public string Damage
		{
			get
			{
				return this._Damage;
			}
			set
			{
				if ((this._Damage != value))
				{
					this.OnDamageChanging(value);
					this.SendPropertyChanging();
					this._Damage = value;
					this.SendPropertyChanged("Damage");
					this.OnDamageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalServiceCost", DbType="Int")]
		public System.Nullable<int> TotalServiceCost
		{
			get
			{
				return this._TotalServiceCost;
			}
			set
			{
				if ((this._TotalServiceCost != value))
				{
					this.OnTotalServiceCostChanging(value);
					this.SendPropertyChanging();
					this._TotalServiceCost = value;
					this.SendPropertyChanged("TotalServiceCost");
					this.OnTotalServiceCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalProductPrice", DbType="Int")]
		public System.Nullable<int> TotalProductPrice
		{
			get
			{
				return this._TotalProductPrice;
			}
			set
			{
				if ((this._TotalProductPrice != value))
				{
					this.OnTotalProductPriceChanging(value);
					this.SendPropertyChanging();
					this._TotalProductPrice = value;
					this.SendPropertyChanged("TotalProductPrice");
					this.OnTotalProductPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalCharge", DbType="Int")]
		public System.Nullable<int> TotalCharge
		{
			get
			{
				return this._TotalCharge;
			}
			set
			{
				if ((this._TotalCharge != value))
				{
					this.OnTotalChargeChanging(value);
					this.SendPropertyChanging();
					this._TotalCharge = value;
					this.SendPropertyChanged("TotalCharge");
					this.OnTotalChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paid", DbType="Int")]
		public System.Nullable<int> Paid
		{
			get
			{
				return this._Paid;
			}
			set
			{
				if ((this._Paid != value))
				{
					this.OnPaidChanging(value);
					this.SendPropertyChanging();
					this._Paid = value;
					this.SendPropertyChanged("Paid");
					this.OnPaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeMoney", DbType="Int")]
		public System.Nullable<int> ChangeMoney
		{
			get
			{
				return this._ChangeMoney;
			}
			set
			{
				if ((this._ChangeMoney != value))
				{
					this.OnChangeMoneyChanging(value);
					this.SendPropertyChanging();
					this._ChangeMoney = value;
					this.SendPropertyChanged("ChangeMoney");
					this.OnChangeMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Char(9)")]
		public string UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserCodeChanging(value);
					this.SendPropertyChanging();
					this._UserCode = value;
					this.SendPropertyChanged("UserCode");
					this.OnUserCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MechanicCode", DbType="Char(5)")]
		public string MechanicCode
		{
			get
			{
				return this._MechanicCode;
			}
			set
			{
				if ((this._MechanicCode != value))
				{
					if (this._Mechanic.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMechanicCodeChanging(value);
					this.SendPropertyChanging();
					this._MechanicCode = value;
					this.SendPropertyChanged("MechanicCode");
					this.OnMechanicCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TransactionService_DetailProduct", Storage="_DetailProducts", ThisKey="TransactionNumber", OtherKey="TransactionNumber")]
		public EntitySet<DetailProduct> DetailProducts
		{
			get
			{
				return this._DetailProducts;
			}
			set
			{
				this._DetailProducts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TransactionService_DetailService", Storage="_DetailServices", ThisKey="TransactionNumber", OtherKey="TransactionNumber")]
		public EntitySet<DetailService> DetailServices
		{
			get
			{
				return this._DetailServices;
			}
			set
			{
				this._DetailServices.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_TransactionService", Storage="_User", ThisKey="UserCode", OtherKey="UserCode", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.TransactionServices.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.TransactionServices.Add(this);
						this._UserCode = value.UserCode;
					}
					else
					{
						this._UserCode = default(string);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mechanic_TransactionService", Storage="_Mechanic", ThisKey="MechanicCode", OtherKey="MechanicCode", IsForeignKey=true)]
		public Mechanic Mechanic
		{
			get
			{
				return this._Mechanic.Entity;
			}
			set
			{
				Mechanic previousValue = this._Mechanic.Entity;
				if (((previousValue != value) 
							|| (this._Mechanic.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Mechanic.Entity = null;
						previousValue.TransactionServices.Remove(this);
					}
					this._Mechanic.Entity = value;
					if ((value != null))
					{
						value.TransactionServices.Add(this);
						this._MechanicCode = value.MechanicCode;
					}
					else
					{
						this._MechanicCode = default(string);
					}
					this.SendPropertyChanged("Mechanic");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DetailProducts(DetailProduct entity)
		{
			this.SendPropertyChanging();
			entity.TransactionService = this;
		}
		
		private void detach_DetailProducts(DetailProduct entity)
		{
			this.SendPropertyChanging();
			entity.TransactionService = null;
		}
		
		private void attach_DetailServices(DetailService entity)
		{
			this.SendPropertyChanging();
			entity.TransactionService = this;
		}
		
		private void detach_DetailServices(DetailService entity)
		{
			this.SendPropertyChanging();
			entity.TransactionService = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MotorcycleServices")]
	public partial class MotorcycleService : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ServiceCode;
		
		private string _ServiceName;
		
		private System.Nullable<int> _Cost;
		
		private EntitySet<DetailService> _DetailServices;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnServiceCodeChanging(string value);
    partial void OnServiceCodeChanged();
    partial void OnServiceNameChanging(string value);
    partial void OnServiceNameChanged();
    partial void OnCostChanging(System.Nullable<int> value);
    partial void OnCostChanged();
    #endregion
		
		public MotorcycleService()
		{
			this._DetailServices = new EntitySet<DetailService>(new Action<DetailService>(this.attach_DetailServices), new Action<DetailService>(this.detach_DetailServices));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceCode", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ServiceCode
		{
			get
			{
				return this._ServiceCode;
			}
			set
			{
				if ((this._ServiceCode != value))
				{
					this.OnServiceCodeChanging(value);
					this.SendPropertyChanging();
					this._ServiceCode = value;
					this.SendPropertyChanged("ServiceCode");
					this.OnServiceCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceName", DbType="VarChar(100)")]
		public string ServiceName
		{
			get
			{
				return this._ServiceName;
			}
			set
			{
				if ((this._ServiceName != value))
				{
					this.OnServiceNameChanging(value);
					this.SendPropertyChanging();
					this._ServiceName = value;
					this.SendPropertyChanged("ServiceName");
					this.OnServiceNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="Int")]
		public System.Nullable<int> Cost
		{
			get
			{
				return this._Cost;
			}
			set
			{
				if ((this._Cost != value))
				{
					this.OnCostChanging(value);
					this.SendPropertyChanging();
					this._Cost = value;
					this.SendPropertyChanged("Cost");
					this.OnCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MotorcycleService_DetailService", Storage="_DetailServices", ThisKey="ServiceCode", OtherKey="ServiceCode")]
		public EntitySet<DetailService> DetailServices
		{
			get
			{
				return this._DetailServices;
			}
			set
			{
				this._DetailServices.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DetailServices(DetailService entity)
		{
			this.SendPropertyChanging();
			entity.MotorcycleService = this;
		}
		
		private void detach_DetailServices(DetailService entity)
		{
			this.SendPropertyChanging();
			entity.MotorcycleService = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Products")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ProductCode;
		
		private string _ProductName;
		
		private System.Nullable<int> _Price;
		
		private EntitySet<DetailProduct> _DetailProducts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductCodeChanging(string value);
    partial void OnProductCodeChanged();
    partial void OnProductNameChanging(string value);
    partial void OnProductNameChanged();
    partial void OnPriceChanging(System.Nullable<int> value);
    partial void OnPriceChanged();
    #endregion
		
		public Product()
		{
			this._DetailProducts = new EntitySet<DetailProduct>(new Action<DetailProduct>(this.attach_DetailProducts), new Action<DetailProduct>(this.detach_DetailProducts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this.OnProductCodeChanging(value);
					this.SendPropertyChanging();
					this._ProductCode = value;
					this.SendPropertyChanged("ProductCode");
					this.OnProductCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="VarChar(100)")]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this.OnProductNameChanging(value);
					this.SendPropertyChanging();
					this._ProductName = value;
					this.SendPropertyChanged("ProductName");
					this.OnProductNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int")]
		public System.Nullable<int> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_DetailProduct", Storage="_DetailProducts", ThisKey="ProductCode", OtherKey="ProductCode")]
		public EntitySet<DetailProduct> DetailProducts
		{
			get
			{
				return this._DetailProducts;
			}
			set
			{
				this._DetailProducts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DetailProducts(DetailProduct entity)
		{
			this.SendPropertyChanging();
			entity.Product = this;
		}
		
		private void detach_DetailProducts(DetailProduct entity)
		{
			this.SendPropertyChanging();
			entity.Product = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mechanics")]
	public partial class Mechanic : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MechanicCode;
		
		private string _MechanicName;
		
		private EntitySet<TransactionService> _TransactionServices;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMechanicCodeChanging(string value);
    partial void OnMechanicCodeChanged();
    partial void OnMechanicNameChanging(string value);
    partial void OnMechanicNameChanged();
    #endregion
		
		public Mechanic()
		{
			this._TransactionServices = new EntitySet<TransactionService>(new Action<TransactionService>(this.attach_TransactionServices), new Action<TransactionService>(this.detach_TransactionServices));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MechanicCode", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MechanicCode
		{
			get
			{
				return this._MechanicCode;
			}
			set
			{
				if ((this._MechanicCode != value))
				{
					this.OnMechanicCodeChanging(value);
					this.SendPropertyChanging();
					this._MechanicCode = value;
					this.SendPropertyChanged("MechanicCode");
					this.OnMechanicCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MechanicName", DbType="VarChar(60)")]
		public string MechanicName
		{
			get
			{
				return this._MechanicName;
			}
			set
			{
				if ((this._MechanicName != value))
				{
					this.OnMechanicNameChanging(value);
					this.SendPropertyChanging();
					this._MechanicName = value;
					this.SendPropertyChanged("MechanicName");
					this.OnMechanicNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mechanic_TransactionService", Storage="_TransactionServices", ThisKey="MechanicCode", OtherKey="MechanicCode")]
		public EntitySet<TransactionService> TransactionServices
		{
			get
			{
				return this._TransactionServices;
			}
			set
			{
				this._TransactionServices.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TransactionServices(TransactionService entity)
		{
			this.SendPropertyChanging();
			entity.Mechanic = this;
		}
		
		private void detach_TransactionServices(TransactionService entity)
		{
			this.SendPropertyChanging();
			entity.Mechanic = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DetailService")]
	public partial class DetailService : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TransactionNumber;
		
		private string _ServiceCode;
		
		private System.Nullable<int> _Cost;
		
		private EntityRef<MotorcycleService> _MotorcycleService;
		
		private EntityRef<TransactionService> _TransactionService;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTransactionNumberChanging(string value);
    partial void OnTransactionNumberChanged();
    partial void OnServiceCodeChanging(string value);
    partial void OnServiceCodeChanged();
    partial void OnCostChanging(System.Nullable<int> value);
    partial void OnCostChanged();
    #endregion
		
		public DetailService()
		{
			this._MotorcycleService = default(EntityRef<MotorcycleService>);
			this._TransactionService = default(EntityRef<TransactionService>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionNumber", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TransactionNumber
		{
			get
			{
				return this._TransactionNumber;
			}
			set
			{
				if ((this._TransactionNumber != value))
				{
					if (this._TransactionService.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTransactionNumberChanging(value);
					this.SendPropertyChanging();
					this._TransactionNumber = value;
					this.SendPropertyChanged("TransactionNumber");
					this.OnTransactionNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceCode", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ServiceCode
		{
			get
			{
				return this._ServiceCode;
			}
			set
			{
				if ((this._ServiceCode != value))
				{
					if (this._MotorcycleService.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnServiceCodeChanging(value);
					this.SendPropertyChanging();
					this._ServiceCode = value;
					this.SendPropertyChanged("ServiceCode");
					this.OnServiceCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="Int")]
		public System.Nullable<int> Cost
		{
			get
			{
				return this._Cost;
			}
			set
			{
				if ((this._Cost != value))
				{
					this.OnCostChanging(value);
					this.SendPropertyChanging();
					this._Cost = value;
					this.SendPropertyChanged("Cost");
					this.OnCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MotorcycleService_DetailService", Storage="_MotorcycleService", ThisKey="ServiceCode", OtherKey="ServiceCode", IsForeignKey=true)]
		public MotorcycleService MotorcycleService
		{
			get
			{
				return this._MotorcycleService.Entity;
			}
			set
			{
				MotorcycleService previousValue = this._MotorcycleService.Entity;
				if (((previousValue != value) 
							|| (this._MotorcycleService.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MotorcycleService.Entity = null;
						previousValue.DetailServices.Remove(this);
					}
					this._MotorcycleService.Entity = value;
					if ((value != null))
					{
						value.DetailServices.Add(this);
						this._ServiceCode = value.ServiceCode;
					}
					else
					{
						this._ServiceCode = default(string);
					}
					this.SendPropertyChanged("MotorcycleService");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TransactionService_DetailService", Storage="_TransactionService", ThisKey="TransactionNumber", OtherKey="TransactionNumber", IsForeignKey=true)]
		public TransactionService TransactionService
		{
			get
			{
				return this._TransactionService.Entity;
			}
			set
			{
				TransactionService previousValue = this._TransactionService.Entity;
				if (((previousValue != value) 
							|| (this._TransactionService.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TransactionService.Entity = null;
						previousValue.DetailServices.Remove(this);
					}
					this._TransactionService.Entity = value;
					if ((value != null))
					{
						value.DetailServices.Add(this);
						this._TransactionNumber = value.TransactionNumber;
					}
					else
					{
						this._TransactionNumber = default(string);
					}
					this.SendPropertyChanged("TransactionService");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
