<?xml version="1.0" encoding="utf-8"?><Database Name="books" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TUFA16\SQLEXPRESS;Initial Catalog=books;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="Books.Properties.Settings" SettingsPropertyName="booksConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.books" Member="books">
    <Type Name="book">
      <Column Name="id" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="book_title" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="author" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="publisher" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="stock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_user" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Association Name="user_book" Member="user" ThisKey="id_user" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.roles" Member="roles">
    <Type Name="role">
      <Column Name="id" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="role_user" Member="users" ThisKey="id" OtherKey="roles_id" Type="user" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="roles_id" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="password_user" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="name_user" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="birthdate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="status_user" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="user_book" Member="books" ThisKey="id" OtherKey="id_user" Type="book" />
      <Association Name="role_user" Member="role" ThisKey="roles_id" OtherKey="id" Type="role" IsForeignKey="true" />
    </Type>
  </Table>
</Database>